#cloud-config
write_files:
  - path: /tmp/hello.txt
    content: |
      Cloud-init is working!
packages:
  - amazon-ssm-agent
runcmd:
  - echo "Cloud-init runcmd executed" >> /tmp/hello.txt
  - systemctl enable amazon-ssm-agent
  - systemctl start amazon-ssm-agent
